#!/usr/bin/env python3
"""Render the shared manuscript body into journal Word templates.

Usage (from anywhere, pandoc >= 3 on PATH, python-docx installed):

    python paper/build_templates.py            # both templates
    python paper/build_templates.py ijies      # one of: ijies, futech

Inputs are body.tex, tables/*.tex (generated by scripts/build_paper_tables.py),
figures/*.png, refs.bib and the two publisher templates in templates/.
Outputs are DES_UCB_IJIES.docx and DES_UCB_Futech.docx next to this file.

Pipeline. body.tex is rewritten so that every \\ref, \\eqref and equation
number is resolved to literal text (Word has no LaTeX counters), the
IEEE-only front matter is removed and template-specific abstracts are added.
pandoc turns that LaTeX into an intermediate .docx (OMML equations, tables,
IEEE-numbered references). The intermediate paragraphs are then re-set into
the publisher template with that template's fonts, sizes, caption forms and
two-column section layout, so headers, footers, margins and styles of the
template are kept untouched.
"""
from __future__ import annotations

import copy
import io
import re
import subprocess
import sys
import zipfile
from dataclasses import dataclass
from pathlib import Path

import docx
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

PAPER = Path(__file__).resolve().parent
TPL = PAPER / "templates"
AUTHORS = "Dhayanidhi Rajasekaran and Rajalakshmi N.R."
TITLE = ("Drift-Triggered Evidence Switching Suppresses Stale Priors in "
         "Cold-Start Interactive Recommendation")
AFFIL = ("Department of Computer Science and Engineering, Vel Tech Rangarajan "
         "Dr Sagunthala R&D Institute of Science and Technology, Chennai, India")
EMAIL = "dhayanidhi.r@gmail.com"
REPO = "https://github.com/dhayarajas/DES-UCB"
KEYWORDS = ("Contextual bandits, concept drift, cold start, interactive "
            "recommendation, non-stationary environments, preregistration")

# Abstracts. Numbers are macros from tables/macros.tex, never typed by hand.
# IJIES asks for at most 150 words. Futech asks for 150 to 250 words with no
# equations, figures, tables or references.
ABSTRACT_IJIES = r"""
A demographic prior serves a new user well at first and turns harmful once taste drifts, because
a warm linear bandit keeps conditioning on stale rows. \des{} is a contextual bandit that holds
a prior-driven source P and a sliding-window feedback source F, picks one each round with EXP3
on a clipped generalisation gain, and on a Page-Hinkley firing halves the window, purges old
feedback, resets the credit of P and forces F for a burn-in. Eight claims were preregistered and
five are supported. On abrupt drift with a stale prior the dynamic regret is \supRegretDES{}
against \supRegretAtwo{} without suppression, paired difference \supDiff{} with 95\% CI [\supLo,
\supHi]. Passive decay of the prior is not worse, the method costs \harmRatio{} times the regret
of warm LinUCB without drift, and MovieLens-1M shows no precision gain. The contribution is a
mechanism, two diagnostics and a preregistered protocol, not a regret win.
"""

ABSTRACT_FUTECH = r"""
A demographic prior serves a new user well from the first round. The same prior turns harmful
once the user's taste drifts, because a warm linear bandit keeps conditioning on rows that no
longer describe the reward. This article studies \des{}, a contextual bandit with two evidence
sources for one reward model. Source P is a ridge estimator fitted on prior rows. Source F is a
sliding-window ridge estimator on the user's own feedback. An EXP3 meta-controller picks the
source for each round and is paid a clipped generalisation gain. A Page-Hinkley detector watches
the squared residual of the active source. When it fires, the agent halves the window, purges
feedback older than the new window, resets the credit of P and forces F for a burn-in. A Bandit-
over-Bandit layer picks the window length between blocks. Eight claims were preregistered and
five are supported. On abrupt drift with a stale prior, \des{} has lower dynamic regret than the
same agent without suppression (\supRegretDES{} against \supRegretAtwo{}, paired difference
\supDiff{} with 95\% CI [\supLo, \supHi]). The same holds with a misspecified population prior.
Post-change rounds spent on P fall from \staleAtwo{} to \staleDES{}. Three claims are not
supported. Passive decay of the prior is not worse than the full purge. With no drift, \des{}
has \harmRatio{} times the regret of warm LinUCB. MovieLens-1M shows no precision gain. The
contribution is a mechanism, two diagnostics and a preregistered protocol with a text gate, not
a regret win.
"""

W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
M_NS = "http://schemas.openxmlformats.org/officeDocument/2006/math"
R_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
A_NS = "http://schemas.openxmlformats.org/drawingml/2006/main"
WP_NS = "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"


# --------------------------------------------------------------------------
# 1. LaTeX preprocessing
# --------------------------------------------------------------------------
@dataclass
class Prepared:
    latex: str
    keywords: str


def _split_rows(body: str) -> list[str]:
    return re.split(r"\\\\(?![a-zA-Z])", body)


def prepare_latex() -> Prepared:
    src = (PAPER / "body.tex").read_text()

    kw = re.search(r"\\begin{IEEEkeywords}(.*?)\\end{IEEEkeywords}", src, re.S).group(1)
    keywords = " ".join(kw.split()).rstrip(".")
    src = re.sub(r"\\begin{abstract}.*?\\end{abstract}\s*", "", src, flags=re.S)
    src = re.sub(r"\\begin{IEEEkeywords}.*?\\end{IEEEkeywords}\s*", "", src, flags=re.S)
    src = re.sub(r"\\section\*{Acknowledgment}.*", "", src, flags=re.S)

    labels: dict[str, str] = {}

    # sections
    s1 = s2 = 0
    def sec(m):
        nonlocal s1, s2
        if m.group(1) == "section":
            s1 += 1; s2 = 0; num = f"{s1}"
        else:
            s2 += 1; num = f"{s1}.{s2}"
        lab = re.match(r"\s*\\label{([^}]*)}", src[m.end():])
        if lab:
            labels[lab.group(1)] = num
        return m.group(0)
    for m in re.finditer(r"\\(section|subsection){([^}]*)}", src):
        sec(m)

    # figures and tables, in source order, span flag from the starred form
    counters = {"figure": 0, "table": 0}
    def float_env(m):
        kind, star = m.group(1), m.group(2)
        counters[kind] += 1
        n = counters[kind]
        lab = re.search(r"\\label{([^}]*)}", m.group(0))
        if lab:
            labels[lab.group(1)] = str(n)
        inner = m.group(0)
        span = bool(star)
        if kind == "table":
            cols = re.search(r"begin{tabular}{([^}]*)}", inner)
            if cols is None:
                inc = re.search(r"\\input{([^}]*)}", inner)
                cols = re.search(r"begin{tabular}{([^}]*)}", (PAPER / (inc.group(1) + ".tex")).read_text())
            ncol = len(re.findall(r"[lrc]|p{[^}]*}", cols.group(1)))
            span = span or ncol > 4
        inner = inner.replace(f"\\begin{{{kind}*}}", f"\\begin{{{kind}}}")
        inner = inner.replace(f"\\end{{{kind}*}}", f"\\end{{{kind}}}")
        if span:
            return "\n\nSPANBEGIN\n\n" + inner + "\n\nSPANEND\n\n"
        return inner
    src = re.sub(r"\\begin{(figure|table)(\*?)}\[[^]]*\].*?\\end{\1\*?}", float_env, src, flags=re.S)

    # equations
    eq = 0
    def equation(m):
        nonlocal eq
        env, inner = m.group(1), m.group(2)
        if env == "equation":
            eq += 1
            lab = re.search(r"\\label{([^}]*)}", inner)
            if lab:
                labels[lab.group(1)] = f"({eq})"
            inner = re.sub(r"\\label{[^}]*}", "", inner)
            return f"\\begin{{equation}}{inner}\\end{{equation}}\n\nEQNUM ({eq})\n\n"
        rows = _split_rows(inner)
        first = None
        for row in rows:
            if not row.strip():
                continue
            if r"\nonumber" in row:
                lab = re.search(r"\\label{([^}]*)}", row)
                if lab:
                    labels[lab.group(1)] = f"({eq + 1})"
                continue
            eq += 1
            first = first or eq
            lab = re.search(r"\\label{([^}]*)}", row)
            if lab:
                labels[lab.group(1)] = f"({eq})"
        inner = re.sub(r"\\label{[^}]*}", "", inner).replace(r"\nonumber", "")
        num = f"({first})" if first == eq else f"({first})\u2013({eq})"
        return f"\\[\\begin{{aligned}}{inner}\\end{{aligned}}\\]\n\nEQNUM {num}\n\n"
    src = re.sub(r"\\begin{(equation|align)}(.*?)\\end{\1}", equation, src, flags=re.S)

    def ref(m):
        key = m.group(2)
        if key not in labels:
            raise KeyError(f"unresolved label {key}")
        val = labels[key]
        if m.group(1) == "eqref":
            return val
        return val
    src = re.sub(r"\\(eqref|ref){([^}]*)}", ref, src)
    src = src.replace("~", " ")

    # squared residuals as sized delimiters so the exponent binds to the group
    src = re.sub(r"(?<![\\\w])\(([^()]*\\hat\\theta[^()]*)\)\^2", r"\\left(\1\\right)^2", src)
    # bare absolute-value bars and half-open intervals come out as unknown
    # glyphs in some Word viewers, so they are written as sized delimiters
    src = re.sub(r"(?<![\\|])\|((?:\\mathcal ?\{?[AW]\}?_?t?|\\hat\\mu_0-\\hat\\mu_1))\|", r"\\left|\1\\right|", src)
    src = src.replace("[kH,(k+1)H)", r"\left[kH,(k+1)H\right)")
    src = re.sub(
        r"\\input{(tables/[^}]*)}",
        lambda m: (PAPER / (m.group(1) + ".tex")).read_text(),
        src,
    )
    src = src.replace("$<$", r"\textless{}").replace(r"$\le$", "\u2264")
    # pandoc cannot read adjustbox or IEEE-only spacing commands
    src = re.sub(r"\\begin{adjustbox}{[^}]*}", "", src)
    src = src.replace(r"\end{adjustbox}", "")
    src = re.sub(r"\\includegraphics\[[^]]*\]{", r"\\includegraphics{", src)

    shim = (PAPER / "docx_shim.tex").read_text()
    macros = (PAPER / "tables" / "macros.tex").read_text()
    latex = (
        shim + macros
        + "\n\nABSTRACTIJIES\n\n" + ABSTRACT_IJIES.strip()
        + "\n\nABSTRACTFUTECH\n\n" + ABSTRACT_FUTECH.strip()
        + "\n\nBODYBEGIN\n\n" + src
    )
    return Prepared(latex=latex, keywords=keywords)


def run_pandoc(latex: str, out: Path) -> None:
    tex = PAPER / ".body_templates.tex"
    tex.write_text(latex)
    cmd = [
        "pandoc", str(tex), "--from", "latex", "--to", "docx",
        f"--resource-path={PAPER}:{PAPER / 'figures'}:{PAPER / 'tables'}",
        "--citeproc", "--bibliography", str(PAPER / "refs.bib"), "--csl", str(PAPER / "ieee.csl"),
        "-o", str(out),
    ]
    res = subprocess.run(cmd, capture_output=True, text=True, cwd=PAPER)
    if res.returncode != 0:
        sys.exit(res.stderr)
    if res.stderr.strip():
        print(res.stderr.strip())
    tex.unlink()


# --------------------------------------------------------------------------
# 2. Template description
# --------------------------------------------------------------------------
@dataclass
class Spec:
    name: str
    template: Path
    output: Path
    font: str
    body_pt: float
    h1_pt: float
    h2_pt: float
    caption_pt: float
    table_pt: float
    ref_pt: float
    fig_prefix: str          # "Figure. {n} " or "Figure {n}. "
    tab_prefix: str          # "Table {n}. " or "Table {n} "
    first_line_indent: int   # twips
    abstract_words: tuple[int, int]
    back_matter: list[tuple[str, str]]


def spec_ijies() -> Spec:
    return Spec(
        name="ijies",
        template=TPL / "IJIES_Format.docx",
        output=PAPER / "DES_UCB_IJIES.docx",
        font="Times New Roman",
        body_pt=11, h1_pt=11, h2_pt=11, caption_pt=10, table_pt=10, ref_pt=11,
        fig_prefix="Figure. {n} ", tab_prefix="Table {n}. ",
        first_line_indent=330,
        abstract_words=(0, 150),
        back_matter=[
            ("Conflicts of interest", "The authors declare no conflict of interest."),
            ("Author contributions",
             "Conceptualization, methodology, software, validation, formal analysis, "
             "investigation, data curation, visualization and writing of the original "
             "draft, Dhayanidhi Rajasekaran. Supervision, review and editing, "
             "Rajalakshmi N.R. Both authors read and approved the final manuscript."),
            ("Acknowledgments",
             "The code, the executed notebook, every result file and the scripts that "
             f"produced the tables in this article are in the repository {REPO}. "
             "This work received no external funding."),
        ],
    )


def spec_futech() -> Spec:
    return Spec(
        name="futech",
        template=TPL / "Futech_Template.docx",
        output=PAPER / "DES_UCB_Futech.docx",
        font="AdvOT596495f2",
        body_pt=9, h1_pt=9, h2_pt=9, caption_pt=9, table_pt=8, ref_pt=9,
        fig_prefix="Figure {n}. ", tab_prefix="Table {n} ",
        first_line_indent=360,
        abstract_words=(150, 250),
        back_matter=[
            ("Acknowledgements",
             "This work received no external funding. The code, the executed notebook, "
             "every result file and the scripts that produced the tables in this "
             f"article are in the repository {REPO}."),
            ("Ethical issue",
             "The authors are aware of and comply with best practices in publication "
             "ethics, specifically with regard to authorship, dual submission, "
             "manipulation of figures, competing interests and compliance with "
             "policies on research ethics. The study uses public benchmark datasets "
             "and synthetic data only. No human participants were recruited."),
            ("Data availability statement",
             "The synthetic environments, the executed notebook and every result "
             f"file behind the tables and figures are in the repository {REPO}. "
             "MovieLens-1M, MovieLens-100K and MIND-small are public datasets and "
             "are downloaded by the notebook from their original hosts."),
            ("Conflict of interest", "The authors declare no potential conflict of interest."),
        ],
    )


# --------------------------------------------------------------------------
# 3. OOXML helpers
# --------------------------------------------------------------------------
def _el(tag: str, **attrs) -> OxmlElement:
    e = OxmlElement(tag)
    for k, v in attrs.items():
        e.set(qn(k), str(v))
    return e


def _rpr(font: str, pt: float, bold=None, italic=None, sup=False) -> OxmlElement:
    rpr = OxmlElement("w:rPr")
    fonts = _el("w:rFonts", **{"w:ascii": font, "w:hAnsi": font, "w:cs": font})
    rpr.append(fonts)
    if bold:
        rpr.append(OxmlElement("w:b"))
    if italic:
        rpr.append(OxmlElement("w:i"))
    hp = str(int(round(pt * 2)))
    rpr.append(_el("w:sz", **{"w:val": hp}))
    rpr.append(_el("w:szCs", **{"w:val": hp}))
    if sup:
        rpr.append(_el("w:vertAlign", **{"w:val": "superscript"}))
    return rpr


def _run(text: str, font: str, pt: float, bold=None, italic=None, sup=False) -> OxmlElement:
    r = OxmlElement("w:r")
    r.append(_rpr(font, pt, bold, italic, sup))
    if text == "\t":
        r.append(OxmlElement("w:tab"))
    else:
        t = _el("w:t", **{"xml:space": "preserve"})
        t.text = text
        r.append(t)
    return r


def _ppr(align=None, before=0, after=0, first_line=None, left=None, hanging=None,
         keep_next=False, tabs=None, line=240) -> OxmlElement:
    ppr = OxmlElement("w:pPr")
    if keep_next:
        ppr.append(OxmlElement("w:keepNext"))
    if tabs:
        t = OxmlElement("w:tabs")
        for val, pos in tabs:
            t.append(_el("w:tab", **{"w:val": val, "w:pos": pos}))
        ppr.append(t)
    ppr.append(_el("w:spacing", **{"w:before": before, "w:after": after,
                                   "w:line": line, "w:lineRule": "auto"}))
    ind = {}
    if first_line is not None:
        ind["w:firstLine"] = first_line
    if left is not None:
        ind["w:left"] = left
    if hanging is not None:
        ind["w:hanging"] = hanging
    if ind:
        ppr.append(_el("w:ind", **ind))
    if align:
        ppr.append(_el("w:jc", **{"w:val": align}))
    return ppr


def _para(ppr: OxmlElement, runs: list[OxmlElement]) -> OxmlElement:
    p = OxmlElement("w:p")
    p.append(ppr)
    for r in runs:
        p.append(r)
    return p


def normalise_runs(container, font: str, pt: float, keep_style_size=False) -> None:
    """Re-set every run under ``container`` in the template font and size.

    Bold, italic and super/subscript from pandoc are kept. Verbatim runs get
    Courier New. Math runs keep their Cambria Math font and get the size only.
    """
    hp = str(int(round(pt * 2)))
    for r in container.iter(qn("w:r")):
        in_math = any(a.tag.startswith("{%s}" % M_NS) for a in r.iterancestors())
        rpr = r.find(qn("w:rPr"))
        if rpr is None:
            rpr = OxmlElement("w:rPr")
            r.insert(0, rpr)
        style = rpr.find(qn("w:rStyle"))
        code = style is not None and "Verbatim" in (style.get(qn("w:val")) or "")
        keep = {}
        for tag in ("w:b", "w:i", "w:vertAlign", "w:u", "w:strike"):
            e = rpr.find(qn(tag))
            if e is not None:
                keep[tag] = e
        for child in list(rpr):
            rpr.remove(child)
        if not in_math:
            f = "Courier New" if code else font
            rpr.append(_el("w:rFonts", **{"w:ascii": f, "w:hAnsi": f, "w:cs": f}))
        for tag in ("w:b", "w:i", "w:u", "w:strike", "w:vertAlign"):
            if tag in keep:
                rpr.append(keep[tag])
        rpr.append(_el("w:sz", **{"w:val": hp}))
        rpr.append(_el("w:szCs", **{"w:val": hp}))


def unwrap_hyperlinks(el) -> None:
    for h in list(el.iter(qn("w:hyperlink"))):
        parent = h.getparent()
        idx = parent.index(h)
        for child in list(h):
            parent.insert(idx, child)
            idx += 1
        parent.remove(h)


def para_text(p) -> str:
    return "".join(t.text or "" for t in p.iter(qn("w:t")))


def content_children(p) -> list:
    """Run-level children of a paragraph (everything except pPr)."""
    return [c for c in p if c.tag != qn("w:pPr")]


# --------------------------------------------------------------------------
# 4. Writer
# --------------------------------------------------------------------------
class Writer:
    def __init__(self, spec: Spec, src_docx: Path, keywords: str):
        self.spec = spec
        self.doc = docx.Document(str(spec.template))
        self.src = docx.Document(str(src_docx))
        self.src_zip = zipfile.ZipFile(src_docx)
        self.keywords = keywords
        self.body = self.doc.element.body
        self.fig = 0
        self.tab = 0
        self.h1 = 0
        self.h2 = 0
        self.image_cache: dict[str, str] = {}
        self.ref_pars: list = []
        # relationship id -> media path in the pandoc package
        rels = self.src.part.rels
        self.src_media = {rid: rel.target_part for rid, rel in rels.items()
                          if rel.reltype.endswith("/image")}

    # -- section geometry -------------------------------------------------
    def _two_col_sectpr(self):
        for sp in self.body.iter(qn("w:sectPr")):
            cols = sp.find(qn("w:cols"))
            if cols is not None and cols.get(qn("w:num")) == "2":
                return sp
        raise RuntimeError("template has no two-column section")

    def geometry(self):
        sp = self._two_col_sectpr()
        pg = sp.find(qn("w:pgSz")); mar = sp.find(qn("w:pgMar")); cols = sp.find(qn("w:cols"))
        text_w = int(pg.get(qn("w:w"))) - int(mar.get(qn("w:left"))) - int(mar.get(qn("w:right")))
        gap = int(cols.get(qn("w:space")))
        col_w = (text_w - gap) // 2
        return text_w, col_w  # twips

    def _sect_break(self, num_cols: int):
        """Paragraph carrying a continuous section break for the section that ends here."""
        sp = copy.deepcopy(self._two_col_sectpr())
        for tag in ("w:headerReference", "w:footerReference"):
            for e in sp.findall(qn(tag)):
                sp.remove(e)
        cols = sp.find(qn("w:cols"))
        if num_cols == 1:
            if cols.get(qn("w:num")) is not None:
                del cols.attrib[qn("w:num")]
        else:
            cols.set(qn("w:num"), "2")
        t = sp.find(qn("w:type"))
        if t is None:
            t = OxmlElement("w:type"); sp.insert(0, t)
        t.set(qn("w:val"), "continuous")
        ppr = _ppr(after=0)
        ppr.append(sp)
        p = OxmlElement("w:p"); p.append(ppr)
        return p

    # -- element emission --------------------------------------------------
    def emit(self, el) -> None:
        self.body.insert(len(self.body) - 1, el)  # before the body sectPr

    def emit_par(self, ppr, runs, pt=None):
        p = _para(ppr, runs)
        self.emit(p)
        return p

    def text_par(self, text, pt=None, bold=False, italic=False, align="both",
                 before=0, after=0, first_line=None, keep_next=False):
        pt = pt or self.spec.body_pt
        return self.emit_par(_ppr(align=align, before=before, after=after,
                                  first_line=first_line, keep_next=keep_next),
                             [_run(text, self.spec.font, pt, bold, italic)])

    # -- images -------------------------------------------------------------
    def relink_images(self, el, max_width_twips: int) -> None:
        for blip in el.iter("{%s}blip" % A_NS):
            rid = blip.get("{%s}embed" % R_NS)
            if rid not in self.image_cache:
                part = self.src_media[rid]
                new_rid, _ = self.doc.part.get_or_add_image(io.BytesIO(part.blob))
                self.image_cache[rid] = new_rid
            blip.set("{%s}embed" % R_NS, self.image_cache[rid])
        max_emu = max_width_twips * 635
        for ext in el.iter("{%s}extent" % WP_NS):
            cx, cy = int(ext.get("cx")), int(ext.get("cy"))
            if cx > max_emu:
                scale = max_emu / cx
                cx, cy = int(cx * scale), int(cy * scale)
            ext.set("cx", str(cx)); ext.set("cy", str(cy))
            drawing = next(a for a in ext.iterancestors() if a.tag == qn("w:drawing"))
            for aext in drawing.iter("{%s}ext" % A_NS):
                aext.set("cx", str(cx)); aext.set("cy", str(cy))

    # -- front matter --------------------------------------------------------
    def clear_par(self, p, keep_ppr=True):
        for c in list(p):
            if c.tag == qn("w:pPr") and keep_ppr:
                # drop paragraph-mark colour/superscript so nothing red survives
                rpr = c.find(qn("w:rPr"))
                if rpr is not None:
                    for tag in ("w:color", "w:vertAlign"):
                        e = rpr.find(qn(tag))
                        if e is not None:
                            rpr.remove(e)
                continue
            p.remove(c)

    def fill_par(self, p, pieces, font, pt):
        """pieces: list of (text, bold, italic, superscript) or lxml run-level elements."""
        self.clear_par(p)
        for piece in pieces:
            if isinstance(piece, tuple):
                text, b, i, s = piece
                p.append(_run(text, font, pt, b, i, s))
            else:
                p.append(piece)

    # -- body conversion -----------------------------------------------------
    def convert_body(self, elements: list) -> None:
        text_w, col_w = self.geometry()
        span = False
        pending_caption = None  # for tables: caption comes before the table
        i = 0
        while i < len(elements):
            el = elements[i]
            i += 1
            if el.tag == qn("w:tbl"):
                self.tab += 1
                if pending_caption is not None:
                    self.emit(pending_caption)
                    pending_caption = None
                self.emit_table(el, text_w if span else col_w)
                continue
            if el.tag != qn("w:p"):
                continue
            style = self._style(el).lower()
            text = para_text(el).strip()
            if text == "SPANBEGIN":
                self.emit(self._sect_break(2)); span = True; continue
            if text == "SPANEND":
                self.emit(self._sect_break(1)); span = False; continue
            if text.startswith("EQNUM"):
                self.attach_eq_number(text.split(None, 1)[1]); continue
            if style.startswith("heading"):
                if style == "heading 1" and text.lower() in ("references", "bibliography"):
                    continue
                self.emit_heading(style, el); continue
            if style in ("image caption", "caption"):
                self.emit_caption(el, "fig", col_w if not span else text_w); continue
            if style == "table caption":
                pending_caption = self.make_caption(el, "tab", text_w if span else col_w); continue
            if style == "bibliography":
                self.emit_reference(el); continue
            has_img = el.find(".//" + qn("w:drawing")) is not None
            if has_img:
                self.emit_image_par(el, text_w if span else col_w); continue
            has_display_math = el.find(qn("m:oMathPara")) is not None or el.find(".//" + qn("m:oMathPara")) is not None
            if has_display_math:
                self.emit_display_math(el, text_w if span else col_w); continue
            self.emit_body_par(el, style)

    def _style(self, p) -> str:
        ps = p.find(qn("w:pPr"))
        if ps is None:
            return "Normal"
        s = ps.find(qn("w:pStyle"))
        if s is None:
            return "Normal"
        sid = s.get(qn("w:val"))
        try:
            return self.src.styles.element.get_by_id(sid).name_val or sid
        except AttributeError:
            return sid

    def _runs_of(self, p, pt):
        p = copy.deepcopy(p)
        unwrap_hyperlinks(p)
        normalise_runs(p, self.spec.font, pt)
        return content_children(p)

    def emit_body_par(self, p, style):
        runs = self._runs_of(p, self.spec.body_pt)
        if not runs:
            return
        self.emit_par(_ppr(align="both", first_line=self.spec.first_line_indent, after=0), runs)

    def emit_heading(self, style, p):
        spec = self.spec
        text = para_text(p).strip()
        if style == "heading 1":
            self.h1 += 1; self.h2 = 0
            label = f"{self.h1}. {text}"
            self.emit_par(_ppr(align="left", before=240, after=120, keep_next=True),
                          [_run(label, spec.font, spec.h1_pt, bold=True)])
        elif style == "heading 2":
            self.h2 += 1
            label = f"{self.h1}.{self.h2}. {text}"
            self.emit_par(_ppr(align="left", before=180, after=100, keep_next=True),
                          [_run(label, spec.font, spec.h2_pt, bold=True)])
        else:
            self.emit_par(_ppr(align="left", before=120, after=60, keep_next=True),
                          [_run(text, spec.font, spec.body_pt, bold=True, italic=True)])

    def make_caption(self, p, kind, width):
        spec = self.spec
        runs = self._runs_of(p, spec.caption_pt)
        # drop a pandoc-generated "Figure 1: " or "Table 1: " prefix if present
        first_t = next((t for t in _para(_ppr(), runs).iter(qn("w:t"))), None)
        if first_t is not None and first_t.text:
            first_t.text = re.sub(r"^(Figure|Table)\s*\d+[:.]?\s*", "", first_t.text)
        if kind == "fig":
            self.fig += 1
            prefix = spec.fig_prefix.format(n=self.fig)
        else:
            prefix = spec.tab_prefix.format(n=self.tab + 1)
        ppr = _ppr(align="center", before=60, after=120 if kind == "fig" else 60,
                   keep_next=(kind == "tab"))
        return _para(ppr, [_run(prefix, spec.font, spec.caption_pt, bold=True)] + runs)

    def emit_caption(self, p, kind, width):
        self.emit(self.make_caption(p, kind, width))

    def emit_image_par(self, p, width):
        p = copy.deepcopy(p)
        self.relink_images(p, width)
        for c in list(p):
            if c.tag == qn("w:pPr"):
                p.remove(c)
        p.insert(0, _ppr(align="center", before=120, after=60, keep_next=True))
        # strip caption runs pandoc may leave inline, keep drawings only
        for r in list(p.iter(qn("w:r"))):
            if r.find(".//" + qn("w:drawing")) is None:
                r.getparent().remove(r)
        self.emit(p)

    def emit_display_math(self, p, width):
        spec = self.spec
        p = copy.deepcopy(p)
        normalise_runs(p, spec.font, spec.body_pt)
        # alignment marks inside equation arrays render as stray symbols in
        # some viewers, so each row is simply centred
        for t in list(p.iter(qn("m:t"))):
            if t.text and "&" in t.text:
                t.text = t.text.replace("&", "")
            if not t.text:
                r = t.getparent()
                r.getparent().remove(r)
        maths = list(p.iter(qn("m:oMathPara")))
        for mp in maths:
            parent = mp.getparent()
            idx = parent.index(mp)
            for om in list(mp.findall(qn("m:oMath"))):
                parent.insert(idx, om); idx += 1
            parent.remove(mp)
        for c in list(p):
            if c.tag == qn("w:pPr"):
                p.remove(c)
        right = width
        p.insert(0, _ppr(align="left", before=60, after=60,
                         tabs=[("center", str(right // 2)), ("right", str(right))]))
        p.insert(1, _run("\t", spec.font, spec.body_pt))
        self._last_math = p
        self.emit(p)

    def attach_eq_number(self, num):
        p = self._last_math
        p.append(_run("\t", self.spec.font, self.spec.body_pt))
        p.append(_run(num, self.spec.font, self.spec.body_pt))

    def emit_reference(self, p):
        spec = self.spec
        runs = self._runs_of(p, spec.ref_pt)
        # pandoc bibliography entries carry the "[n]" label then a tab
        p = self.emit_par(_ppr(align="both", left=440, hanging=440, after=40,
                               tabs=[("left", "440")]), runs)
        self.ref_pars.append(p)

    def emit_table(self, tbl, width):
        spec = self.spec
        tbl = copy.deepcopy(tbl)
        unwrap_hyperlinks(tbl)
        normalise_runs(tbl, spec.font, spec.table_pt)
        tblpr = tbl.find(qn("w:tblPr"))
        if tblpr is None:
            tblpr = OxmlElement("w:tblPr"); tbl.insert(0, tblpr)
        for tag in ("w:tblStyle", "w:tblW", "w:jc", "w:tblBorders", "w:tblLook", "w:tblInd"):
            for e in tblpr.findall(qn(tag)):
                tblpr.remove(e)
        tblpr.insert(0, _el("w:tblStyle", **{"w:val": self._table_style_id()}))
        tblpr.append(_el("w:tblW", **{"w:w": str(width), "w:type": "dxa"}))
        tblpr.append(_el("w:jc", **{"w:val": "center"}))
        tblpr.append(_el("w:tblLayout", **{"w:type": "autofit"}))
        # grid widths proportional to the longest entry of each column, so
        # numeric columns stay narrow and text columns get the room
        rows = tbl.findall(qn("w:tr"))
        ncol = max(len(r.findall(qn("w:tc"))) for r in rows)
        longest = [1] * ncol
        for r in rows:
            for j, tc in enumerate(r.findall(qn("w:tc"))):
                words = para_text(tc).split()
                est = min(max([len(x) for x in words] + [0]) + 2 + len(para_text(tc)) // 4, 40)
                longest[j] = max(longest[j], est)
        total = sum(longest)
        widths = [max(500, width * l // total) for l in longest]
        scale = width / sum(widths)
        widths = [int(x * scale) for x in widths]
        grid = tbl.find(qn("w:tblGrid"))
        if grid is None:
            grid = OxmlElement("w:tblGrid"); tblpr.addnext(grid)
        for gc in list(grid):
            grid.remove(gc)
        for wdt in widths:
            grid.append(_el("w:gridCol", **{"w:w": str(wdt)}))
        for r in rows:
            for j, tc in enumerate(r.findall(qn("w:tc"))):
                tcpr = tc.find(qn("w:tcPr"))
                if tcpr is None:
                    tcpr = OxmlElement("w:tcPr"); tc.insert(0, tcpr)
                for e in tcpr.findall(qn("w:tcW")):
                    tcpr.remove(e)
                tcpr.insert(0, _el("w:tcW", **{"w:w": str(widths[j]), "w:type": "dxa"}))
        for tc in tbl.iter(qn("w:tc")):
            for p in tc.findall(qn("w:p")):
                ppr = p.find(qn("w:pPr"))
                if ppr is not None:
                    p.remove(ppr)
                p.insert(0, _ppr(after=0, line=240))
        self.emit(tbl)
        self.emit_par(_ppr(after=120), [])

    def _table_style_id(self) -> str:
        for s in self.doc.styles:
            if s.name == "Table Grid":
                return s.style_id
        # create a minimal grid style if the template lacks one
        st = self.doc.styles.add_style("Table Grid", docx.enum.style.WD_STYLE_TYPE.TABLE)
        borders = parse_xml(
            '<w:tblBorders %s>' % nsdecls("w")
            + "".join(f'<w:{b} w:val="single" w:sz="4" w:space="0" w:color="auto"/>'
                      for b in ("top", "left", "bottom", "right", "insideH", "insideV"))
            + "</w:tblBorders>")
        tblpr = st.element.get_or_add_tblPr()
        tblpr.append(borders)
        return st.style_id

    # -- back matter ---------------------------------------------------------
    def emit_back_matter(self):
        spec = self.spec
        for head, text in spec.back_matter:
            self.emit_par(_ppr(align="left", before=240, after=120, keep_next=True),
                          [_run(head, spec.font, spec.h1_pt, bold=True)])
            self.text_par(text, first_line=spec.first_line_indent)

    def save(self):
        self.doc.save(str(self.spec.output))
        print("wrote", self.spec.output.relative_to(PAPER.parent))


# --------------------------------------------------------------------------
# 5. Per-template assembly
# --------------------------------------------------------------------------
def split_source(src_doc) -> dict[str, list]:
    """Cut the pandoc body at the marker paragraphs."""
    parts: dict[str, list] = {"ABSTRACTIJIES": [], "ABSTRACTFUTECH": [], "BODYBEGIN": []}
    cur = None
    for el in src_doc.element.body.iterchildren():
        if el.tag == qn("w:sectPr"):
            continue
        t = para_text(el).strip() if el.tag == qn("w:p") else ""
        if t in parts:
            cur = t; continue
        if cur:
            parts[cur].append(el)
    return parts


def abstract_runs(w: Writer, paras: list, pt: float) -> list:
    runs = []
    for p in paras:
        runs += w._runs_of(p, pt)
    return runs


def check_abstract(paras, lo, hi, name):
    words = " ".join(para_text(p) for p in paras).split()
    n = len(words)
    if not (lo <= n <= hi):
        sys.exit(f"{name} abstract has {n} words, template allows {lo}-{hi}")
    print(f"{name} abstract: {n} words")


def build_ijies(src_docx: Path, keywords: str):
    spec = spec_ijies()
    w = Writer(spec, src_docx, keywords)
    parts = split_source(w.src)
    check_abstract(parts["ABSTRACTIJIES"], *spec.abstract_words, "IJIES")
    body = w.body
    children = list(body.iterchildren())
    paras = [c for c in children if c.tag == qn("w:p")]

    # front matter paragraphs of the template, by position
    title_p, authors_p, affil1_p, affil2_p, corr_p, abs_p, kw_p = (
        paras[1], paras[3], paras[5], paras[6], paras[7], paras[10], paras[11])
    F = spec.font
    w.fill_par(title_p, [(TITLE, True, False, False)], F, 14)
    w.fill_par(authors_p, [("Dhayanidhi Rajasekaran", True, False, False), ("1*", True, False, True),
                           ("          ", True, False, False),
                           ("Rajalakshmi N.R.", True, False, False), ("2", True, False, True)], F, 11)
    w.fill_par(affil1_p, [("1", False, True, True), ("Research Scholar, " + AFFIL, False, True, False)], F, 10.5)
    w.fill_par(affil2_p, [("2", False, True, True), ("Professor, " + AFFIL, False, True, False)], F, 10.5)
    w.fill_par(corr_p, [("* Corresponding author\u2019s Email: " + EMAIL, False, False, False)], F, 10)
    w.fill_par(abs_p, [("Abstract: ", True, False, False)] + abstract_runs(w, parts["ABSTRACTIJIES"], 10), F, 10)
    w.fill_par(kw_p, [("Keywords: ", True, False, False), (keywords, False, False, False)], F, 10)

    # the running header carries sample editorial dates, which the journal fills in
    for section in w.doc.sections:
        for hp in section.header.paragraphs:
            if "Received:" in hp.text:
                runs = hp.runs
                seen_revised = False
                for i, r in enumerate(runs):
                    seen_revised = seen_revised or "Revised" in r.text
                    done = seen_revised and r.text.endswith(".")
                    r.text = "Received:" + " " * 16 + "Revised:" if i == 0 else ""
                    if done:
                        break
        for fp in section.footer.paragraphs:
            if "10.22266" in fp.text:
                for r in fp.runs:
                    if "10.22266" in r.text:
                        r.text = "DOI:"
                    elif r.text in ("9", ".xxxx.xx"):
                        r.text = ""

    # the section that ends the front matter must stay single column. The
    # body sectPr (end of document) becomes the two-column one.
    two_col = None
    for p in paras:
        sp = p.find(".//" + qn("w:sectPr"))
        if sp is not None and sp.find(qn("w:cols")) is not None and sp.find(qn("w:cols")).get(qn("w:num")) == "2":
            two_col = copy.deepcopy(sp)
    body_sect = body.find(qn("w:sectPr"))
    body.replace(body_sect, two_col)

    # remove every template element after the front-matter section break
    first_sect_par = next(p for p in paras if p.find(".//" + qn("w:sectPr")) is not None)
    idx = list(body).index(first_sect_par)
    for el in list(body)[idx + 1:]:
        if el.tag != qn("w:sectPr"):
            body.remove(el)

    w.convert_body(parts["BODYBEGIN"])
    # pandoc leaves the references at the end of the body under Bibliography
    # style and they were emitted in place. Insert the heading before them.
    w.emit_back_matter()
    move_references_last(w)
    w.save()


def build_futech(src_docx: Path, keywords: str):
    spec = spec_futech()
    w = Writer(spec, src_docx, keywords)
    parts = split_source(w.src)
    check_abstract(parts["ABSTRACTFUTECH"], *spec.abstract_words, "Futech")
    body = w.body
    children = list(body.iterchildren())
    paras = [c for c in children if c.tag == qn("w:p")]
    F = spec.font
    # 2 "Article", 3 title, 4 authors, 5-7 affiliations, table = article info
    w.fill_par(paras[3], [(TITLE, True, False, False)], F, 22)
    w.fill_par(paras[4], [("Dhayanidhi Rajasekaran", True, False, False), ("1*", True, False, True),
                          (", Rajalakshmi N.R.", True, False, False), ("2", True, False, True)], F, 12)
    w.fill_par(paras[5], [("1", False, False, True), ("Research Scholar, " + AFFIL, False, False, False)], F, 10)
    w.fill_par(paras[6], [("2", False, False, True), ("Professor, " + AFFIL, False, False, False)], F, 10)
    body.remove(paras[7])

    # sample publication metadata (issue line, DOI) is filled in by the
    # publisher, so the sample values are blanked rather than kept
    for p in body.iter(qn("w:p")):
        t = para_text(p)
        if "Volume 01" in t or "doi.org/10.55670" in t:
            for r in p.findall(qn("w:r")):
                if r.find(".//" + qn("w:drawing")) is None:
                    p.remove(r)
    for section in w.doc.sections:
        for hp in section.header.paragraphs:
            if "First author" in hp.text:
                blank = False
                for r in hp.runs:
                    if "First author" in r.text:
                        r.text = r.text.replace("First author", "Rajasekaran")
                    if r.text.strip() == "May":
                        blank = True
                    if blank:
                        r.text = ""

    info = w.doc.tables[0]
    left, right = info.rows[0].cells
    for p in left.paragraphs:
        t = p.text.strip()
        if t.startswith("3-6 keywords"):
            w.fill_par(p._p, [(keywords, False, False, False)], F, 9)
        elif t.startswith("Email address"):
            w.fill_par(p._p, [("Email address: " + EMAIL, False, False, False)], F, 9)
        elif t.startswith("Received 00"):
            w.fill_par(p._p, [("Received", False, False, False)], F, 9)
        elif t.startswith("00 April") or t.startswith("DOI:"):
            p._p.getparent().remove(p._p)
        elif t.startswith("Accepted 00"):
            w.fill_par(p._p, [("Accepted", False, False, False)], F, 9)
    rp = right.paragraphs
    # keep "A B S T R A C T" and the blank line, replace the rest by the abstract
    for p in rp[2:]:
        p._p.getparent().remove(p._p)
    abs_p = copy.deepcopy(rp[1]._p)
    right._tc.append(abs_p)
    w.fill_par(abs_p, abstract_runs(w, parts["ABSTRACTFUTECH"], 9), F, 9)
    abs_p.find(qn("w:pPr")).append(_el("w:jc", **{"w:val": "both"}))

    first_sect_par = next(p for p in paras if p.find(".//" + qn("w:sectPr")) is not None)
    idx = list(body).index(first_sect_par)
    for el in list(body)[idx + 1:]:
        if el.tag != qn("w:sectPr"):
            body.remove(el)

    w.convert_body(parts["BODYBEGIN"])
    w.emit_back_matter()
    move_references_last(w)
    blank_sample_text(w, ("10.55670",))
    w.save()


def blank_sample_text(w: Writer, needles):
    """Blank text runs carrying sample publisher metadata in the body and in
    every header and footer, including text boxes."""
    roots = [w.doc.element]
    for s in w.doc.sections:
        roots += [s.header._element, s.footer._element,
                  s.first_page_header._element, s.first_page_footer._element]
    for root in roots:
        for t in root.iter(qn("w:t")):
            if t.text and any(n in t.text for n in needles):
                t.text = ""


def move_references_last(w: Writer):
    """References were converted in place (before the back matter). Move them
    after the back matter under a 'References' heading, as both templates ask."""
    body = w.body
    refs = w.ref_pars
    if not refs:
        return
    sect = body.find(qn("w:sectPr"))
    head = _para(_ppr(align="left", before=240, after=120, keep_next=True),
                 [_run("References", w.spec.font, w.spec.h1_pt, bold=True)])
    body.insert(list(body).index(sect), head)
    for p in refs:
        body.remove(p)
        body.insert(list(body).index(sect), p)


def main(argv):
    which = set(argv[1:]) or {"ijies", "futech"}
    prep = prepare_latex()
    tmp = PAPER / ".templates_pandoc.docx"
    run_pandoc(prep.latex, tmp)
    if "ijies" in which:
        build_ijies(tmp, prep.keywords)
    if "futech" in which:
        build_futech(tmp, prep.keywords)
    tmp.unlink()


if __name__ == "__main__":
    main(sys.argv)
